name: pkgdown

on:
  push:
    branches: [main, master]
    paths:
      - '**.R'
      - '**.Rmd'
      - 'man/**'
      - 'NAMESPACE'
      - 'DESCRIPTION'
      - '_pkgdown.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_CONFIG_AUTOLOADER_ENABLED: "false"
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown
          needs: website

      - name: Clean prebuilt vignettes and docs
        run: |
          rm -rf vignettes/*.html
          rm -rf docs

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = TRUE)
        shell: Rscript {0}

      - name: Debug: List rendered article files
        run: ls -lR docs/articles
