name: R-CMD-check
on:
  push: {branches: [main, master]}
  pull_request: {branches: [main, master]}

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_CONFIG_AUTOLOADER_ENABLED: "false"
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::pak
          needs: check
      - uses: r-lib/actions/check-r-package@v2
